language: generic
env:
  global:
  - GCP_PROJECT_ID=pgr301-exam-hannarong
  - tf_version=0.13.4
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: ksEPMYvv0/lawaNVSD8Edt75H9RBHXkEnFplLQBs0NT6V6l4wduTe/SK5C43m9sPYAtDTQQOqXyOSYUM0spjmTPFbdtLtEofM4ZBwZsLpi3U7BSQjswiCn1MGR+Hfnlodq34QWm9NakrIa+Tk5IsPFVil2paOkZM1do3rqtPCIgvmjSwbJ+aMsBdLTEEIxcG0NuyQMSW88NKk6EsNUlXGLq70dLIe46IX9DUhFEKEL4ehxlzY4ITzWgMigDBVYl4vMQXMPBGM+yyAQWLeC1ywLyA8GOxp1yEWLsX5H6LLgVdo97UGLDBkj2U4OmeXkJfVMG/N2iJSKjML7HBkarDLk8at8uoTDa0d1zCMwSg1WYFWDW1KS2dMvPYQ5BnyMImF6G/WguHhqmux3fGhWWEHLyBm9UEi1+K3yo1H1NoZizJpQtX2MGsl79Zv9RJJSKAjNVKW4tbaoV0PVPIowjrXiCS1sSju18eZjfA4QNC/Ad8rooJ849428dC9vDMylFU5hdb+XK9AJvmvcbHNrIj4dcqMuMfNfwTizR6rkYImxHRrBh5B+fom1RY3kOeyQp17/mt/7SiAAwPSSF90/v7EBkrgaK3m1axcjP8QHJ6Zi2ixHlvdM6fbrZ2NSmOY3fWa6EwYkunbQIdujmLnyNINSMALA49aXvUHcj2K5g6Qhg=
  - secure: vG1M+6X7X8aAJWUnu9zqIcys/sUF0/gerTK72QF1VQEsuNoSvbRbKocO4RHIgOO5oesgDnmMYo/hu4mHrOoEc8pX0f46s5Wtx+ID2IcrPqA1pm9YrZbEoGIeY3eXu8dsnS6oXGOvG2EyIRNJGGBMVeamvN6Qh6tzTe9us8MyznxoTTUHc1pbM6nEWeDnVrJHU0LwnWD/2S54BJiSeEXyilFTilVXa7H7b5zP9WDwBSWXXzEVJOEOB0CSdiv/dUkpX71YSnxoRtlG9BS4IkMpfvwiBCLrNpH0qV4t3WrYsMHUSun6n73G/EPZ0ns4WpgxLHFTVvP89STySjrPpktW2d0YFGJ4xiCPARzDWEc3dFbsrkAyY+lOIiXJVmWPkTNFm9zgwP2OqqWqNr0sN8ihESQeO/iIgJ96vHmdbk1DI1RkTZw4r7/Y/NIryfIGQtmw8QQt4s/it8JmwsoJX9nNLy9XH5woB+DJU3EH9y5aIZir1+unHawXJOH2o9nxx6PLLCktQjc+ppBPHkgmJcCxm0fBtSZDq59OvXboXLo8+oSGD1/+N3F+8NDB7+/+exR/gCU7LTeEbRaWVYmVxvU1z24U5uok7b638bu6ZTSYXXT6suiUtvDZiWmcwLEAxOxMpRkpnqRB11BkGWbfd66JvUQOtMAs76kBjfUrdpFNC/k=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_e1915bc0061f_key -iv $encrypted_e1915bc0061f_iv
  -in terraform-credentials.json.enc -out terraform-credentials.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=terraform-credentials.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./terraform-credentials.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  export TF_VAR_logz_url=$LOGZ_URL
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
