language: generic
env:
  global:
  - GCP_PROJECT_ID=pgr301-exam-hannarong-296202
  - tf_version=0.13.4
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: ksEPMYvv0/lawaNVSD8Edt75H9RBHXkEnFplLQBs0NT6V6l4wduTe/SK5C43m9sPYAtDTQQOqXyOSYUM0spjmTPFbdtLtEofM4ZBwZsLpi3U7BSQjswiCn1MGR+Hfnlodq34QWm9NakrIa+Tk5IsPFVil2paOkZM1do3rqtPCIgvmjSwbJ+aMsBdLTEEIxcG0NuyQMSW88NKk6EsNUlXGLq70dLIe46IX9DUhFEKEL4ehxlzY4ITzWgMigDBVYl4vMQXMPBGM+yyAQWLeC1ywLyA8GOxp1yEWLsX5H6LLgVdo97UGLDBkj2U4OmeXkJfVMG/N2iJSKjML7HBkarDLk8at8uoTDa0d1zCMwSg1WYFWDW1KS2dMvPYQ5BnyMImF6G/WguHhqmux3fGhWWEHLyBm9UEi1+K3yo1H1NoZizJpQtX2MGsl79Zv9RJJSKAjNVKW4tbaoV0PVPIowjrXiCS1sSju18eZjfA4QNC/Ad8rooJ849428dC9vDMylFU5hdb+XK9AJvmvcbHNrIj4dcqMuMfNfwTizR6rkYImxHRrBh5B+fom1RY3kOeyQp17/mt/7SiAAwPSSF90/v7EBkrgaK3m1axcjP8QHJ6Zi2ixHlvdM6fbrZ2NSmOY3fWa6EwYkunbQIdujmLnyNINSMALA49aXvUHcj2K5g6Qhg=
  - secure: vG1M+6X7X8aAJWUnu9zqIcys/sUF0/gerTK72QF1VQEsuNoSvbRbKocO4RHIgOO5oesgDnmMYo/hu4mHrOoEc8pX0f46s5Wtx+ID2IcrPqA1pm9YrZbEoGIeY3eXu8dsnS6oXGOvG2EyIRNJGGBMVeamvN6Qh6tzTe9us8MyznxoTTUHc1pbM6nEWeDnVrJHU0LwnWD/2S54BJiSeEXyilFTilVXa7H7b5zP9WDwBSWXXzEVJOEOB0CSdiv/dUkpX71YSnxoRtlG9BS4IkMpfvwiBCLrNpH0qV4t3WrYsMHUSun6n73G/EPZ0ns4WpgxLHFTVvP89STySjrPpktW2d0YFGJ4xiCPARzDWEc3dFbsrkAyY+lOIiXJVmWPkTNFm9zgwP2OqqWqNr0sN8ihESQeO/iIgJ96vHmdbk1DI1RkTZw4r7/Y/NIryfIGQtmw8QQt4s/it8JmwsoJX9nNLy9XH5woB+DJU3EH9y5aIZir1+unHawXJOH2o9nxx6PLLCktQjc+ppBPHkgmJcCxm0fBtSZDq59OvXboXLo8+oSGD1/+N3F+8NDB7+/+exR/gCU7LTeEbRaWVYmVxvU1z24U5uok7b638bu6ZTSYXXT6suiUtvDZiWmcwLEAxOxMpRkpnqRB11BkGWbfd66JvUQOtMAs76kBjfUrdpFNC/k=
  - secure: H70oAEfYWneuT4rFsI7OR5ahV3+1qYEE87XXFyjfY7OVZipF8hqXYF247oR22ex0HA3Um8ufi7gFx60tDOV/7Mmk1J2tItiuKxOWyjFM/o4HrJZSAXYPpbc6sBEGG9G8litC2Knn6iIk6cRtnZ6jj+926diqHkQ9qSs7YfR2wrV5YFppW44THwAoujswW1SOOUDVTfEJtr9jRsLiME+SFNPjLC5r898Dcz1ptsW9mhhcoRo8KNxfJiFLBKwNJVGV00cd3XRCJmGPZS1K/4uQDKVir6lB++YTxc8nSAt1PtSWJ+XYAnVvv9WCTn1vaPQCjCvoyGAfuxS6SrcSroyyS2r0o1XNxc9YhNgFw1s2pKoD43mA/9bBYQdwmgIDubg48shCG8JLaZ7r/FBurS5ruQq78FYQp6LKeZ8L8LulGkfAH7ILMenEfbPMgYcMxJVPO93u5QvJBXtu255OvIrxCHNWnDGKzTZHG0uncbfr3PptJpKI58whzFKOr/I4MZrcYU0uqPk9lGHWfh2e4pmFpmISe8z9QtijWdNGAOYnu5Vsw2sziPv0AlYpDYtJ3ccY4bmMXRlEv4Atd+zS1rzE/DBvhsTfKEfyTrNGrdH5UOoasOcKmhcCtrFPquIkR6AF/28dxYoEVQK2x5fD0JOX+UJ9HjttocgFOim9WBQgiCI=
  - secure: pGsVuuNSZHasEpiKXu/CYPeB7Ff5Sg1FcjaQ9aY6fJqAqplf30UptfBu17lGJZpqgKj1dpv7OQQU4O3i9vSJPmi3veUlfCXL6LvGlVXLRWkCzsWPsy56wNwLFLUM3jANXUx2Heqtc/AGrULyWa1UFO1offN1v3nHBh/trQCRqaqiyq+sxkmICF28pjf5Cbv7lTt7KDayKP5DPA+sYJokysazD/Km9Ci2w3FohdHxJtfpHZfmm1F1WEQaNDZit1cji0p7W0rJ3W2l4cDxbQyzmc3CPlo6xzXX7EbD8yQNKSvw/+V1ZeJUM7sifJJvkcsSsLGpEtGtThIrEWwnH+FsG8/H2p8tIft2DLj0jw1dGP4axGi1A7l6oCVXAa4+4C3mY+ze4oqDL+Quz6kg9lZEDvYVsLxRgf1C25CFEq0wcRtjCga47X9I9xJn6aGNTg9f9wlCILYnnLFY/+3WbDgrlF6hf+kii47WUq4ZWvlvZYLaAPpgq9CKa9pTV+8fX69ifw+pXQsb2UIinTp5X9OpBtTI+39RKJMWxScrfYxlj47c+K9PdKsGpBeRFU8kbqq/eHYocE4FDj/8tSxkna9V414YyiMff6W+yLXYYwETfn+QjNO5KOHYsV/AHlQfJ2xK2mxpTxKp5kQP9XrSEw8ZR/2AzrpA9i7Zcaoe/JIcH2k=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_e1915bc0061f_key -iv $encrypted_e1915bc0061f_iv
  -in terraform-credentials.json.enc -out terraform-credentials.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=terraform-credentials.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./terraform-credentials.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  export TF_VAR_logz_url=$LOGZ_URL
  export TF_VAR_status_cake_username=$STATUS_CAKE_USERNAME
  export TF_VAR_status_cake_api_key=$STATUS_CAKE_API_KEY
  terraform init
  terraform plan
  terraform destroy
  terraform apply --auto-approve
  terraform output
